_target_: sde_sampler.models.mlp.FourierMLP
dim: ${target.dim}
num_layers: 4
channels: 64
activation: 
  _target_: torch.nn.GELU
last_bias_init:
  _target_: sde_sampler.models.utils.init_bias_uniform_zeros
  _partial_: True
last_weight_init:
  _target_: sde_sampler.models.utils.kaiming_uniform_zeros_
  _partial_: True
use_angle_encoding: False