defaults:
  - base@score_model: time_embed
  - base@base_model: fouriermlp
  - _self_

_target_: sde_sampler.models.reparam.CancelDriftCtrl
detach_score: False
score_model:
  last_bias_init:
    _target_: sde_sampler.models.utils.init_bias_uniform_constant
    val: 1.
    _partial_: True
clip_score: 1e4
clip_model: 1e4
langevin_init: True
