# @package _global_
defaults:
  - basic_oc_base
  - /prior: gauss
  - /sde: controlled_langevin
  - /model@generative_ctrl: basic
  - /loss: controlled_sde_lv
  - _self_

# Solver
solver:
  _target_: sde_sampler.solver.oc.CMCD

prior:
  scale: 5.0 # to change wrt the target
