# @package _global_
defaults:
  - basic_oc_base
  - /prior: gauss
  - /sde: 
  - /model@generative_ctrl: score
  - /loss: exponential_sde_lv
  - _self_

# Solver
solver:
  _target_: sde_sampler.solver.oc.DDS

train_timesteps:
  rescale_t: "cosine"
  steps: 
  end: 6.4
  dt: 0.05

prior:
  scale: ${loss.sigma}
