# @package _global_
defaults:
  - basic_oc_base
  - /prior: gauss
  - /sde: vp_10
  - /model@generative_ctrl: lerp
  - /loss: time_reversal_lv
  - _self_

# Solver
solver:
  _target_: sde_sampler.solver.oc.Bridge

prior:
  scale: ${sde.scale_diff_coeff}